@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jun 22 15:20:54 +0530 2026
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 0fadcfae3e054427986c044403daf9ef --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L secureip --snapshot tb_tagger_extracted_func_impl xil_defaultlib.tb_tagger_extracted xil_defaultlib.glbl -log elaborate.log -transport_int_delays -pulse_r 0 -pulse_int_r 0"
call xelab  -wto 0fadcfae3e054427986c044403daf9ef --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L secureip --snapshot tb_tagger_extracted_func_impl xil_defaultlib.tb_tagger_extracted xil_defaultlib.glbl -log elaborate.log -transport_int_delays -pulse_r 0 -pulse_int_r 0
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
