#
# $Id: red_pitaya.xdc 961 2014-01-21 11:40:39Z matej.oblak $
#
# @brief Red Pitaya location constraints.
#
# @Author Matej Oblak
#
# (c) Red Pitaya  http://www.redpitaya.com
#

############################################################################
# IO constraints                                                           #
############################################################################

### ADC

# ADC data
set_property IOSTANDARD LVCMOS18 [get_ports {adc_dat_i[*][*]}]
set_property IOB        TRUE     [get_ports {adc_dat_i[*][*]}]

# ADC 0 data
set_property PACKAGE_PIN V17     [get_ports {adc_dat_i[0][0]}]
set_property PACKAGE_PIN U17     [get_ports {adc_dat_i[0][1]}]
set_property PACKAGE_PIN Y17     [get_ports {adc_dat_i[0][2]}]
set_property PACKAGE_PIN W16     [get_ports {adc_dat_i[0][3]}]
set_property PACKAGE_PIN Y16     [get_ports {adc_dat_i[0][4]}]
set_property PACKAGE_PIN W15     [get_ports {adc_dat_i[0][5]}]
set_property PACKAGE_PIN W14     [get_ports {adc_dat_i[0][6]}]
set_property PACKAGE_PIN Y14     [get_ports {adc_dat_i[0][7]}]
set_property PACKAGE_PIN W13     [get_ports {adc_dat_i[0][8]}]
set_property PACKAGE_PIN V12     [get_ports {adc_dat_i[0][9]}]
set_property PACKAGE_PIN V13     [get_ports {adc_dat_i[0][10]}]
set_property PACKAGE_PIN T14     [get_ports {adc_dat_i[0][11]}]
set_property PACKAGE_PIN T15     [get_ports {adc_dat_i[0][12]}]
set_property PACKAGE_PIN V15     [get_ports {adc_dat_i[0][13]}]
set_property PACKAGE_PIN T16     [get_ports {adc_dat_i[0][14]}]
set_property PACKAGE_PIN V16     [get_ports {adc_dat_i[0][15]}]

# ADC 1 data
set_property PACKAGE_PIN T17     [get_ports {adc_dat_i[1][0]}]
set_property PACKAGE_PIN R16     [get_ports {adc_dat_i[1][1]}]
set_property PACKAGE_PIN R18     [get_ports {adc_dat_i[1][2]}]
set_property PACKAGE_PIN P16     [get_ports {adc_dat_i[1][3]}]
set_property PACKAGE_PIN P18     [get_ports {adc_dat_i[1][4]}]
set_property PACKAGE_PIN N17     [get_ports {adc_dat_i[1][5]}]
set_property PACKAGE_PIN R19     [get_ports {adc_dat_i[1][6]}]
set_property PACKAGE_PIN T20     [get_ports {adc_dat_i[1][7]}]
set_property PACKAGE_PIN T19     [get_ports {adc_dat_i[1][8]}]
set_property PACKAGE_PIN U20     [get_ports {adc_dat_i[1][9]}]
set_property PACKAGE_PIN V20     [get_ports {adc_dat_i[1][10]}]
set_property PACKAGE_PIN W20     [get_ports {adc_dat_i[1][11]}]
set_property PACKAGE_PIN W19     [get_ports {adc_dat_i[1][12]}]
set_property PACKAGE_PIN Y19     [get_ports {adc_dat_i[1][13]}]
set_property PACKAGE_PIN W18     [get_ports {adc_dat_i[1][14]}]
set_property PACKAGE_PIN Y18     [get_ports {adc_dat_i[1][15]}]

set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc_clk_i[*]]
set_property PACKAGE_PIN U18           [get_ports adc_clk_i[1]]
set_property PACKAGE_PIN U19           [get_ports adc_clk_i[0]]

# Output ADC clock
set_property IOSTANDARD LVCMOS18 [get_ports {adc_clk_o[*]}]
set_property SLEW       FAST     [get_ports {adc_clk_o[*]}]
set_property DRIVE      8        [get_ports {adc_clk_o[*]}]
#set_property IOB        TRUE     [get_ports {adc_clk_o[*]}]

set_property PACKAGE_PIN N20 [get_ports {adc_clk_o[0]}]
set_property PACKAGE_PIN P20 [get_ports {adc_clk_o[1]}]

# ADC clock stabilizer
set_property IOSTANDARD  LVCMOS18 [get_ports adc_cdcs_o]
set_property PACKAGE_PIN V18     [get_ports adc_cdcs_o]
set_property SLEW        FAST     [get_ports adc_cdcs_o]
set_property DRIVE       8        [get_ports adc_cdcs_o]

### DAC

# data
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dat_o[*]}]
set_property SLEW       SLOW     [get_ports {dac_dat_o[*]}]
set_property DRIVE      8        [get_ports {dac_dat_o[*]}]
#set_property IOB        TRUE     [get_ports {dac_dat_o[*]}]

set_property PACKAGE_PIN M19 [get_ports {dac_dat_o[0]}]
set_property PACKAGE_PIN M20 [get_ports {dac_dat_o[1]}]
set_property PACKAGE_PIN L19 [get_ports {dac_dat_o[2]}]
set_property PACKAGE_PIN L20 [get_ports {dac_dat_o[3]}]
set_property PACKAGE_PIN K19 [get_ports {dac_dat_o[4]}]
set_property PACKAGE_PIN J19 [get_ports {dac_dat_o[5]}]
set_property PACKAGE_PIN J20 [get_ports {dac_dat_o[6]}]
set_property PACKAGE_PIN H20 [get_ports {dac_dat_o[7]}]
set_property PACKAGE_PIN G19 [get_ports {dac_dat_o[8]}]
set_property PACKAGE_PIN G20 [get_ports {dac_dat_o[9]}]
set_property PACKAGE_PIN F19 [get_ports {dac_dat_o[10]}]
set_property PACKAGE_PIN F20 [get_ports {dac_dat_o[11]}]
set_property PACKAGE_PIN D20 [get_ports {dac_dat_o[12]}]
set_property PACKAGE_PIN D19 [get_ports {dac_dat_o[13]}]

# control
set_property IOSTANDARD LVCMOS33 [get_ports dac_*_o]
set_property SLEW       FAST     [get_ports dac_*_o]
set_property DRIVE      8        [get_ports dac_*_o]
#set_property IOB        TRUE     [get_ports dac_*_o]

set_property PACKAGE_PIN M17 [get_ports dac_wrt_o]
set_property PACKAGE_PIN N16 [get_ports dac_sel_o]
set_property PACKAGE_PIN M18 [get_ports dac_clk_o]
set_property PACKAGE_PIN N15 [get_ports dac_rst_o]

### PWM DAC
set_property IOSTANDARD LVCMOS18 [get_ports {dac_pwm_o[*]}]
set_property SLEW       FAST     [get_ports {dac_pwm_o[*]}]
set_property DRIVE      12       [get_ports {dac_pwm_o[*]}]
set_property IOB        TRUE     [get_ports {dac_pwm_o[*]}]

set_property PACKAGE_PIN T10 [get_ports {dac_pwm_o[0]}]
set_property PACKAGE_PIN T11 [get_ports {dac_pwm_o[1]}]
set_property PACKAGE_PIN P15 [get_ports {dac_pwm_o[2]}]
set_property PACKAGE_PIN U13 [get_ports {dac_pwm_o[3]}]

### XADC
set_property IOSTANDARD LVCMOS33 [get_ports {vinp_i[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vinn_i[*]}]
#AD0
set_property PACKAGE_PIN C20 [get_ports {vinp_i[1]}]
set_property PACKAGE_PIN B20 [get_ports {vinn_i[1]}]
#AD1
set_property PACKAGE_PIN E17 [get_ports {vinp_i[2]}]
set_property PACKAGE_PIN D18 [get_ports {vinn_i[2]}]
#AD8
set_property PACKAGE_PIN B19 [get_ports {vinp_i[0]}]
set_property PACKAGE_PIN A20 [get_ports {vinn_i[0]}]
#AD9
set_property PACKAGE_PIN E18 [get_ports {vinp_i[3]}]
set_property PACKAGE_PIN E19 [get_ports {vinn_i[3]}]
#V_0
set_property PACKAGE_PIN K9  [get_ports {vinp_i[4]}]
set_property PACKAGE_PIN L10 [get_ports {vinn_i[4]}]

### Expansion connector
set_property SLEW       FAST     [get_ports {exp_p_io[*]}]
set_property SLEW       FAST     [get_ports {exp_n_io[*]}]
set_property DRIVE      8        [get_ports {exp_p_io[*]}]
set_property DRIVE      8        [get_ports {exp_n_io[*]}]


set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[0]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[0]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[1]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[1]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[2]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[2]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[3]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[3]}]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[4]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[4]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[5]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[5]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[6]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[6]}]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {exp_p_io[7]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {exp_n_io[7]}]

#set_property PULLDOWN TRUE [get_ports {exp_p_io[0]}]
#set_property PULLDOWN TRUE [get_ports {exp_n_io[0]}]
#set_property PULLUP   TRUE [get_ports {exp_p_io[7]}]
#set_property PULLUP   TRUE [get_ports {exp_n_io[7]}]

set_property PACKAGE_PIN T12 [get_ports {daisy_p_o[0]}]
set_property PACKAGE_PIN U12 [get_ports {daisy_n_o[0]}]
set_property PACKAGE_PIN U14 [get_ports {daisy_p_o[1]}]
set_property PACKAGE_PIN U15 [get_ports {daisy_n_o[1]}]
set_property PACKAGE_PIN P14 [get_ports {daisy_p_i[0]}]
set_property PACKAGE_PIN R14 [get_ports {daisy_n_i[0]}]
set_property PACKAGE_PIN N18 [get_ports {daisy_p_i[1]}]
set_property PACKAGE_PIN P19 [get_ports {daisy_n_i[1]}]

### LED
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[*]}]
set_property SLEW       SLOW     [get_ports {led_o[*]}]
set_property DRIVE      4        [get_ports {led_o[*]}]

set_property PACKAGE_PIN F16     [get_ports {led_o[0]}]
set_property PACKAGE_PIN F17     [get_ports {led_o[1]}]
set_property PACKAGE_PIN G15     [get_ports {led_o[2]}]
set_property PACKAGE_PIN H15     [get_ports {led_o[3]}]
set_property PACKAGE_PIN K14     [get_ports {led_o[4]}]
set_property PACKAGE_PIN G14     [get_ports {led_o[5]}]
set_property PACKAGE_PIN J15     [get_ports {led_o[6]}]
set_property PACKAGE_PIN J14     [get_ports {led_o[7]}]


set_false_path -from [get_ports {exp_p_io[0]}]
set_false_path -from [get_ports {exp_p_io[1]}]

set_property PULLDOWN true [get_ports spad_ttl_ch0]
set_property PULLDOWN true [get_ports spad_ttl_ch1]
# =============================================================================
# CH0: CARRY4 BELs and sampling FFs both in SLICE_X38Y22-Y85
# =============================================================================
set_property LOC SLICE_X38Y22 [get_cells {i_quantum_tagger/tdl_gen[0].first_block.carry_ch0}]
set_property LOC SLICE_X38Y23 [get_cells {i_quantum_tagger/tdl_gen[1].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y24 [get_cells {i_quantum_tagger/tdl_gen[2].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y25 [get_cells {i_quantum_tagger/tdl_gen[3].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y26 [get_cells {i_quantum_tagger/tdl_gen[4].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y27 [get_cells {i_quantum_tagger/tdl_gen[5].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y28 [get_cells {i_quantum_tagger/tdl_gen[6].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y29 [get_cells {i_quantum_tagger/tdl_gen[7].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y30 [get_cells {i_quantum_tagger/tdl_gen[8].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y31 [get_cells {i_quantum_tagger/tdl_gen[9].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y32 [get_cells {i_quantum_tagger/tdl_gen[10].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y33 [get_cells {i_quantum_tagger/tdl_gen[11].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y34 [get_cells {i_quantum_tagger/tdl_gen[12].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y35 [get_cells {i_quantum_tagger/tdl_gen[13].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y36 [get_cells {i_quantum_tagger/tdl_gen[14].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y37 [get_cells {i_quantum_tagger/tdl_gen[15].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y38 [get_cells {i_quantum_tagger/tdl_gen[16].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y39 [get_cells {i_quantum_tagger/tdl_gen[17].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y40 [get_cells {i_quantum_tagger/tdl_gen[18].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y41 [get_cells {i_quantum_tagger/tdl_gen[19].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y42 [get_cells {i_quantum_tagger/tdl_gen[20].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y43 [get_cells {i_quantum_tagger/tdl_gen[21].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y44 [get_cells {i_quantum_tagger/tdl_gen[22].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y45 [get_cells {i_quantum_tagger/tdl_gen[23].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y46 [get_cells {i_quantum_tagger/tdl_gen[24].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y47 [get_cells {i_quantum_tagger/tdl_gen[25].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y48 [get_cells {i_quantum_tagger/tdl_gen[26].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y49 [get_cells {i_quantum_tagger/tdl_gen[27].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y50 [get_cells {i_quantum_tagger/tdl_gen[28].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y51 [get_cells {i_quantum_tagger/tdl_gen[29].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y52 [get_cells {i_quantum_tagger/tdl_gen[30].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y53 [get_cells {i_quantum_tagger/tdl_gen[31].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y54 [get_cells {i_quantum_tagger/tdl_gen[32].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y55 [get_cells {i_quantum_tagger/tdl_gen[33].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y56 [get_cells {i_quantum_tagger/tdl_gen[34].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y57 [get_cells {i_quantum_tagger/tdl_gen[35].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y58 [get_cells {i_quantum_tagger/tdl_gen[36].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y59 [get_cells {i_quantum_tagger/tdl_gen[37].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y60 [get_cells {i_quantum_tagger/tdl_gen[38].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y61 [get_cells {i_quantum_tagger/tdl_gen[39].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y62 [get_cells {i_quantum_tagger/tdl_gen[40].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y63 [get_cells {i_quantum_tagger/tdl_gen[41].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y64 [get_cells {i_quantum_tagger/tdl_gen[42].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y65 [get_cells {i_quantum_tagger/tdl_gen[43].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y66 [get_cells {i_quantum_tagger/tdl_gen[44].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y67 [get_cells {i_quantum_tagger/tdl_gen[45].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y68 [get_cells {i_quantum_tagger/tdl_gen[46].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y69 [get_cells {i_quantum_tagger/tdl_gen[47].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y70 [get_cells {i_quantum_tagger/tdl_gen[48].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y71 [get_cells {i_quantum_tagger/tdl_gen[49].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y72 [get_cells {i_quantum_tagger/tdl_gen[50].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y73 [get_cells {i_quantum_tagger/tdl_gen[51].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y74 [get_cells {i_quantum_tagger/tdl_gen[52].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y75 [get_cells {i_quantum_tagger/tdl_gen[53].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y76 [get_cells {i_quantum_tagger/tdl_gen[54].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y77 [get_cells {i_quantum_tagger/tdl_gen[55].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y78 [get_cells {i_quantum_tagger/tdl_gen[56].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y79 [get_cells {i_quantum_tagger/tdl_gen[57].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y80 [get_cells {i_quantum_tagger/tdl_gen[58].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y81 [get_cells {i_quantum_tagger/tdl_gen[59].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y82 [get_cells {i_quantum_tagger/tdl_gen[60].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y83 [get_cells {i_quantum_tagger/tdl_gen[61].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y84 [get_cells {i_quantum_tagger/tdl_gen[62].cascade_blocks.carry_ch0}]
set_property LOC SLICE_X38Y85 [get_cells {i_quantum_tagger/tdl_gen[63].cascade_blocks.carry_ch0}]

# CH0 sampling FFs - next column X39
set_property LOC SLICE_X39Y22 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[0]}]
set_property LOC SLICE_X39Y22 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[1]}]
set_property LOC SLICE_X39Y22 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[2]}]
set_property LOC SLICE_X39Y22 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[3]}]
set_property LOC SLICE_X39Y23 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[4]}]
set_property LOC SLICE_X39Y23 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[5]}]
set_property LOC SLICE_X39Y23 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[6]}]
set_property LOC SLICE_X39Y23 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[7]}]
set_property LOC SLICE_X39Y24 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[8]}]
set_property LOC SLICE_X39Y24 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[9]}]
set_property LOC SLICE_X39Y24 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[10]}]
set_property LOC SLICE_X39Y24 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[11]}]
set_property LOC SLICE_X39Y25 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[12]}]
set_property LOC SLICE_X39Y25 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[13]}]
set_property LOC SLICE_X39Y25 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[14]}]
set_property LOC SLICE_X39Y25 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[15]}]
set_property LOC SLICE_X39Y26 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[16]}]
set_property LOC SLICE_X39Y26 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[17]}]
set_property LOC SLICE_X39Y26 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[18]}]
set_property LOC SLICE_X39Y26 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[19]}]
set_property LOC SLICE_X39Y27 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[20]}]
set_property LOC SLICE_X39Y27 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[21]}]
set_property LOC SLICE_X39Y27 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[22]}]
set_property LOC SLICE_X39Y27 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[23]}]
set_property LOC SLICE_X39Y28 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[24]}]
set_property LOC SLICE_X39Y28 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[25]}]
set_property LOC SLICE_X39Y28 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[26]}]
set_property LOC SLICE_X39Y28 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[27]}]
set_property LOC SLICE_X39Y29 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[28]}]
set_property LOC SLICE_X39Y29 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[29]}]
set_property LOC SLICE_X39Y29 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[30]}]
set_property LOC SLICE_X39Y29 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[31]}]
set_property LOC SLICE_X39Y30 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[32]}]
set_property LOC SLICE_X39Y30 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[33]}]
set_property LOC SLICE_X39Y30 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[34]}]
set_property LOC SLICE_X39Y30 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[35]}]
set_property LOC SLICE_X39Y31 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[36]}]
set_property LOC SLICE_X39Y31 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[37]}]
set_property LOC SLICE_X39Y31 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[38]}]
set_property LOC SLICE_X39Y31 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[39]}]
set_property LOC SLICE_X39Y32 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[40]}]
set_property LOC SLICE_X39Y32 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[41]}]
set_property LOC SLICE_X39Y32 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[42]}]
set_property LOC SLICE_X39Y32 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[43]}]
set_property LOC SLICE_X39Y33 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[44]}]
set_property LOC SLICE_X39Y33 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[45]}]
set_property LOC SLICE_X39Y33 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[46]}]
set_property LOC SLICE_X39Y33 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[47]}]
set_property LOC SLICE_X39Y34 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[48]}]
set_property LOC SLICE_X39Y34 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[49]}]
set_property LOC SLICE_X39Y34 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[50]}]
set_property LOC SLICE_X39Y34 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[51]}]
set_property LOC SLICE_X39Y35 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[52]}]
set_property LOC SLICE_X39Y35 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[53]}]
set_property LOC SLICE_X39Y35 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[54]}]
set_property LOC SLICE_X39Y35 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[55]}]
set_property LOC SLICE_X39Y36 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[56]}]
set_property LOC SLICE_X39Y36 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[57]}]
set_property LOC SLICE_X39Y36 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[58]}]
set_property LOC SLICE_X39Y36 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[59]}]
set_property LOC SLICE_X39Y37 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[60]}]
set_property LOC SLICE_X39Y37 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[61]}]
set_property LOC SLICE_X39Y37 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[62]}]
set_property LOC SLICE_X39Y37 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[63]}]
set_property LOC SLICE_X39Y38 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[64]}]
set_property LOC SLICE_X39Y38 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[65]}]
set_property LOC SLICE_X39Y38 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[66]}]
set_property LOC SLICE_X39Y38 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[67]}]
set_property LOC SLICE_X39Y39 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[68]}]
set_property LOC SLICE_X39Y39 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[69]}]
set_property LOC SLICE_X39Y39 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[70]}]
set_property LOC SLICE_X39Y39 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[71]}]
set_property LOC SLICE_X39Y40 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[72]}]
set_property LOC SLICE_X39Y40 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[73]}]
set_property LOC SLICE_X39Y40 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[74]}]
set_property LOC SLICE_X39Y40 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[75]}]
set_property LOC SLICE_X39Y41 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[76]}]
set_property LOC SLICE_X39Y41 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[77]}]
set_property LOC SLICE_X39Y41 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[78]}]
set_property LOC SLICE_X39Y41 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[79]}]
set_property LOC SLICE_X39Y42 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[80]}]
set_property LOC SLICE_X39Y42 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[81]}]
set_property LOC SLICE_X39Y42 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[82]}]
set_property LOC SLICE_X39Y42 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[83]}]
set_property LOC SLICE_X39Y43 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[84]}]
set_property LOC SLICE_X39Y43 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[85]}]
set_property LOC SLICE_X39Y43 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[86]}]
set_property LOC SLICE_X39Y43 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[87]}]
set_property LOC SLICE_X39Y44 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[88]}]
set_property LOC SLICE_X39Y44 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[89]}]
set_property LOC SLICE_X39Y44 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[90]}]
set_property LOC SLICE_X39Y44 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[91]}]
set_property LOC SLICE_X39Y45 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[92]}]
set_property LOC SLICE_X39Y45 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[93]}]
set_property LOC SLICE_X39Y45 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[94]}]
set_property LOC SLICE_X39Y45 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[95]}]
set_property LOC SLICE_X39Y46 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[96]}]
set_property LOC SLICE_X39Y46 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[97]}]
set_property LOC SLICE_X39Y46 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[98]}]
set_property LOC SLICE_X39Y46 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[99]}]
set_property LOC SLICE_X39Y47 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[100]}]
set_property LOC SLICE_X39Y47 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[101]}]
set_property LOC SLICE_X39Y47 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[102]}]
set_property LOC SLICE_X39Y47 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[103]}]
set_property LOC SLICE_X39Y48 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[104]}]
set_property LOC SLICE_X39Y48 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[105]}]
set_property LOC SLICE_X39Y48 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[106]}]
set_property LOC SLICE_X39Y48 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[107]}]
set_property LOC SLICE_X39Y49 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[108]}]
set_property LOC SLICE_X39Y49 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[109]}]
set_property LOC SLICE_X39Y49 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[110]}]
set_property LOC SLICE_X39Y49 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[111]}]
set_property LOC SLICE_X39Y50 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[112]}]
set_property LOC SLICE_X39Y50 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[113]}]
set_property LOC SLICE_X39Y50 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[114]}]
set_property LOC SLICE_X39Y50 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[115]}]
set_property LOC SLICE_X39Y51 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[116]}]
set_property LOC SLICE_X39Y51 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[117]}]
set_property LOC SLICE_X39Y51 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[118]}]
set_property LOC SLICE_X39Y51 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[119]}]
set_property LOC SLICE_X39Y52 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[120]}]
set_property LOC SLICE_X39Y52 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[121]}]
set_property LOC SLICE_X39Y52 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[122]}]
set_property LOC SLICE_X39Y52 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[123]}]
set_property LOC SLICE_X39Y53 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[124]}]
set_property LOC SLICE_X39Y53 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[125]}]
set_property LOC SLICE_X39Y53 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[126]}]
set_property LOC SLICE_X39Y53 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[127]}]
set_property LOC SLICE_X39Y54 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[128]}]
set_property LOC SLICE_X39Y54 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[129]}]
set_property LOC SLICE_X39Y54 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[130]}]
set_property LOC SLICE_X39Y54 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[131]}]
set_property LOC SLICE_X39Y55 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[132]}]
set_property LOC SLICE_X39Y55 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[133]}]
set_property LOC SLICE_X39Y55 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[134]}]
set_property LOC SLICE_X39Y55 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[135]}]
set_property LOC SLICE_X39Y56 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[136]}]
set_property LOC SLICE_X39Y56 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[137]}]
set_property LOC SLICE_X39Y56 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[138]}]
set_property LOC SLICE_X39Y56 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[139]}]
set_property LOC SLICE_X39Y57 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[140]}]
set_property LOC SLICE_X39Y57 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[141]}]
set_property LOC SLICE_X39Y57 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[142]}]
set_property LOC SLICE_X39Y57 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[143]}]
set_property LOC SLICE_X39Y58 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[144]}]
set_property LOC SLICE_X39Y58 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[145]}]
set_property LOC SLICE_X39Y58 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[146]}]
set_property LOC SLICE_X39Y58 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[147]}]
set_property LOC SLICE_X39Y59 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[148]}]
set_property LOC SLICE_X39Y59 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[149]}]
set_property LOC SLICE_X39Y59 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[150]}]
set_property LOC SLICE_X39Y59 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[151]}]
set_property LOC SLICE_X39Y60 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[152]}]
set_property LOC SLICE_X39Y60 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[153]}]
set_property LOC SLICE_X39Y60 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[154]}]
set_property LOC SLICE_X39Y60 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[155]}]
set_property LOC SLICE_X39Y61 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[156]}]
set_property LOC SLICE_X39Y61 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[157]}]
set_property LOC SLICE_X39Y61 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[158]}]
set_property LOC SLICE_X39Y61 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[159]}]
set_property LOC SLICE_X39Y62 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[160]}]
set_property LOC SLICE_X39Y62 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[161]}]
set_property LOC SLICE_X39Y62 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[162]}]
set_property LOC SLICE_X39Y62 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[163]}]
set_property LOC SLICE_X39Y63 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[164]}]
set_property LOC SLICE_X39Y63 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[165]}]
set_property LOC SLICE_X39Y63 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[166]}]
set_property LOC SLICE_X39Y63 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[167]}]
set_property LOC SLICE_X39Y64 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[168]}]
set_property LOC SLICE_X39Y64 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[169]}]
set_property LOC SLICE_X39Y64 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[170]}]
set_property LOC SLICE_X39Y64 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[171]}]
set_property LOC SLICE_X39Y65 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[172]}]
set_property LOC SLICE_X39Y65 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[173]}]
set_property LOC SLICE_X39Y65 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[174]}]
set_property LOC SLICE_X39Y65 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[175]}]
set_property LOC SLICE_X39Y66 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[176]}]
set_property LOC SLICE_X39Y66 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[177]}]
set_property LOC SLICE_X39Y66 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[178]}]
set_property LOC SLICE_X39Y66 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[179]}]
set_property LOC SLICE_X39Y67 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[180]}]
set_property LOC SLICE_X39Y67 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[181]}]
set_property LOC SLICE_X39Y67 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[182]}]
set_property LOC SLICE_X39Y67 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[183]}]
set_property LOC SLICE_X39Y68 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[184]}]
set_property LOC SLICE_X39Y68 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[185]}]
set_property LOC SLICE_X39Y68 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[186]}]
set_property LOC SLICE_X39Y68 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[187]}]
set_property LOC SLICE_X39Y69 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[188]}]
set_property LOC SLICE_X39Y69 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[189]}]
set_property LOC SLICE_X39Y69 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[190]}]
set_property LOC SLICE_X39Y69 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[191]}]
set_property LOC SLICE_X39Y70 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[192]}]
set_property LOC SLICE_X39Y70 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[193]}]
set_property LOC SLICE_X39Y70 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[194]}]
set_property LOC SLICE_X39Y70 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[195]}]
set_property LOC SLICE_X39Y71 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[196]}]
set_property LOC SLICE_X39Y71 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[197]}]
set_property LOC SLICE_X39Y71 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[198]}]
set_property LOC SLICE_X39Y71 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[199]}]
set_property LOC SLICE_X39Y72 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[200]}]
set_property LOC SLICE_X39Y72 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[201]}]
set_property LOC SLICE_X39Y72 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[202]}]
set_property LOC SLICE_X39Y72 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[203]}]
set_property LOC SLICE_X39Y73 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[204]}]
set_property LOC SLICE_X39Y73 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[205]}]
set_property LOC SLICE_X39Y73 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[206]}]
set_property LOC SLICE_X39Y73 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[207]}]
set_property LOC SLICE_X39Y74 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[208]}]
set_property LOC SLICE_X39Y74 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[209]}]
set_property LOC SLICE_X39Y74 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[210]}]
set_property LOC SLICE_X39Y74 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[211]}]
set_property LOC SLICE_X39Y75 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[212]}]
set_property LOC SLICE_X39Y75 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[213]}]
set_property LOC SLICE_X39Y75 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[214]}]
set_property LOC SLICE_X39Y75 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[215]}]
set_property LOC SLICE_X39Y76 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[216]}]
set_property LOC SLICE_X39Y76 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[217]}]
set_property LOC SLICE_X39Y76 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[218]}]
set_property LOC SLICE_X39Y76 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[219]}]
set_property LOC SLICE_X39Y77 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[220]}]
set_property LOC SLICE_X39Y77 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[221]}]
set_property LOC SLICE_X39Y77 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[222]}]
set_property LOC SLICE_X39Y77 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[223]}]
set_property LOC SLICE_X39Y78 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[224]}]
set_property LOC SLICE_X39Y78 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[225]}]
set_property LOC SLICE_X39Y78 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[226]}]
set_property LOC SLICE_X39Y78 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[227]}]
set_property LOC SLICE_X39Y79 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[228]}]
set_property LOC SLICE_X39Y79 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[229]}]
set_property LOC SLICE_X39Y79 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[230]}]
set_property LOC SLICE_X39Y79 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[231]}]
set_property LOC SLICE_X39Y80 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[232]}]
set_property LOC SLICE_X39Y80 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[233]}]
set_property LOC SLICE_X39Y80 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[234]}]
set_property LOC SLICE_X39Y80 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[235]}]
set_property LOC SLICE_X39Y81 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[236]}]
set_property LOC SLICE_X39Y81 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[237]}]
set_property LOC SLICE_X39Y81 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[238]}]
set_property LOC SLICE_X39Y81 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[239]}]
set_property LOC SLICE_X39Y82 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[240]}]
set_property LOC SLICE_X39Y82 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[241]}]
set_property LOC SLICE_X39Y82 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[242]}]
set_property LOC SLICE_X39Y82 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[243]}]
set_property LOC SLICE_X39Y83 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[244]}]
set_property LOC SLICE_X39Y83 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[245]}]
set_property LOC SLICE_X39Y83 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[246]}]
set_property LOC SLICE_X39Y83 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[247]}]
set_property LOC SLICE_X39Y84 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[248]}]
set_property LOC SLICE_X39Y84 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[249]}]
set_property LOC SLICE_X39Y84 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[250]}]
set_property LOC SLICE_X39Y84 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[251]}]
set_property LOC SLICE_X39Y85 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[252]}]
set_property LOC SLICE_X39Y85 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[253]}]
set_property LOC SLICE_X39Y85 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[254]}]
set_property LOC SLICE_X39Y85 [get_cells {i_quantum_tagger/r_tdl_ch0_d_reg[255]}]




# =============================================================================
# CH1: CARRY4 BELs and sampling FFs both in SLICE_X41Y22-Y85
# =============================================================================
set_property LOC SLICE_X41Y22 [get_cells {i_quantum_tagger/tdl_gen[0].first_block.carry_ch1}]
set_property LOC SLICE_X41Y23 [get_cells {i_quantum_tagger/tdl_gen[1].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y24 [get_cells {i_quantum_tagger/tdl_gen[2].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y25 [get_cells {i_quantum_tagger/tdl_gen[3].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y26 [get_cells {i_quantum_tagger/tdl_gen[4].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y27 [get_cells {i_quantum_tagger/tdl_gen[5].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y28 [get_cells {i_quantum_tagger/tdl_gen[6].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y29 [get_cells {i_quantum_tagger/tdl_gen[7].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y30 [get_cells {i_quantum_tagger/tdl_gen[8].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y31 [get_cells {i_quantum_tagger/tdl_gen[9].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y32 [get_cells {i_quantum_tagger/tdl_gen[10].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y33 [get_cells {i_quantum_tagger/tdl_gen[11].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y34 [get_cells {i_quantum_tagger/tdl_gen[12].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y35 [get_cells {i_quantum_tagger/tdl_gen[13].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y36 [get_cells {i_quantum_tagger/tdl_gen[14].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y37 [get_cells {i_quantum_tagger/tdl_gen[15].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y38 [get_cells {i_quantum_tagger/tdl_gen[16].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y39 [get_cells {i_quantum_tagger/tdl_gen[17].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y40 [get_cells {i_quantum_tagger/tdl_gen[18].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y41 [get_cells {i_quantum_tagger/tdl_gen[19].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y42 [get_cells {i_quantum_tagger/tdl_gen[20].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y43 [get_cells {i_quantum_tagger/tdl_gen[21].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y44 [get_cells {i_quantum_tagger/tdl_gen[22].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y45 [get_cells {i_quantum_tagger/tdl_gen[23].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y46 [get_cells {i_quantum_tagger/tdl_gen[24].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y47 [get_cells {i_quantum_tagger/tdl_gen[25].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y48 [get_cells {i_quantum_tagger/tdl_gen[26].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y49 [get_cells {i_quantum_tagger/tdl_gen[27].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y50 [get_cells {i_quantum_tagger/tdl_gen[28].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y51 [get_cells {i_quantum_tagger/tdl_gen[29].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y52 [get_cells {i_quantum_tagger/tdl_gen[30].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y53 [get_cells {i_quantum_tagger/tdl_gen[31].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y54 [get_cells {i_quantum_tagger/tdl_gen[32].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y55 [get_cells {i_quantum_tagger/tdl_gen[33].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y56 [get_cells {i_quantum_tagger/tdl_gen[34].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y57 [get_cells {i_quantum_tagger/tdl_gen[35].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y58 [get_cells {i_quantum_tagger/tdl_gen[36].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y59 [get_cells {i_quantum_tagger/tdl_gen[37].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y60 [get_cells {i_quantum_tagger/tdl_gen[38].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y61 [get_cells {i_quantum_tagger/tdl_gen[39].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y62 [get_cells {i_quantum_tagger/tdl_gen[40].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y63 [get_cells {i_quantum_tagger/tdl_gen[41].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y64 [get_cells {i_quantum_tagger/tdl_gen[42].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y65 [get_cells {i_quantum_tagger/tdl_gen[43].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y66 [get_cells {i_quantum_tagger/tdl_gen[44].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y67 [get_cells {i_quantum_tagger/tdl_gen[45].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y68 [get_cells {i_quantum_tagger/tdl_gen[46].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y69 [get_cells {i_quantum_tagger/tdl_gen[47].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y70 [get_cells {i_quantum_tagger/tdl_gen[48].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y71 [get_cells {i_quantum_tagger/tdl_gen[49].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y72 [get_cells {i_quantum_tagger/tdl_gen[50].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y73 [get_cells {i_quantum_tagger/tdl_gen[51].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y74 [get_cells {i_quantum_tagger/tdl_gen[52].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y75 [get_cells {i_quantum_tagger/tdl_gen[53].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y76 [get_cells {i_quantum_tagger/tdl_gen[54].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y77 [get_cells {i_quantum_tagger/tdl_gen[55].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y78 [get_cells {i_quantum_tagger/tdl_gen[56].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y79 [get_cells {i_quantum_tagger/tdl_gen[57].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y80 [get_cells {i_quantum_tagger/tdl_gen[58].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y81 [get_cells {i_quantum_tagger/tdl_gen[59].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y82 [get_cells {i_quantum_tagger/tdl_gen[60].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y83 [get_cells {i_quantum_tagger/tdl_gen[61].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y84 [get_cells {i_quantum_tagger/tdl_gen[62].cascade_blocks.carry_ch1}]
set_property LOC SLICE_X41Y85 [get_cells {i_quantum_tagger/tdl_gen[63].cascade_blocks.carry_ch1}]

# =========================================================================
# ? CHANNEL 1 PIPELINED TDC LOCATIONS (SLICE COLUMN X42)
# =========================================================================
set_property LOC SLICE_X42Y22 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[0]}]
set_property LOC SLICE_X42Y22 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[1]}]
set_property LOC SLICE_X42Y22 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[2]}]
set_property LOC SLICE_X42Y22 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[3]}]
set_property LOC SLICE_X42Y23 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[4]}]
set_property LOC SLICE_X42Y23 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[5]}]
set_property LOC SLICE_X42Y23 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[6]}]
set_property LOC SLICE_X42Y23 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[7]}]
set_property LOC SLICE_X42Y24 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[8]}]
set_property LOC SLICE_X42Y24 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[9]}]
set_property LOC SLICE_X42Y24 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[10]}]
set_property LOC SLICE_X42Y24 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[11]}]
set_property LOC SLICE_X42Y25 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[12]}]
set_property LOC SLICE_X42Y25 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[13]}]
set_property LOC SLICE_X42Y25 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[14]}]
set_property LOC SLICE_X42Y25 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[15]}]
set_property LOC SLICE_X42Y26 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[16]}]
set_property LOC SLICE_X42Y26 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[17]}]
set_property LOC SLICE_X42Y26 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[18]}]
set_property LOC SLICE_X42Y26 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[19]}]
set_property LOC SLICE_X42Y27 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[20]}]
set_property LOC SLICE_X42Y27 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[21]}]
set_property LOC SLICE_X42Y27 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[22]}]
set_property LOC SLICE_X42Y27 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[23]}]
set_property LOC SLICE_X42Y28 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[24]}]
set_property LOC SLICE_X42Y28 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[25]}]
set_property LOC SLICE_X42Y28 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[26]}]
set_property LOC SLICE_X42Y28 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[27]}]
set_property LOC SLICE_X42Y29 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[28]}]
set_property LOC SLICE_X42Y29 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[29]}]
set_property LOC SLICE_X42Y29 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[30]}]
set_property LOC SLICE_X42Y29 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[31]}]
set_property LOC SLICE_X42Y30 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[32]}]
set_property LOC SLICE_X42Y30 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[33]}]
set_property LOC SLICE_X42Y30 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[34]}]
set_property LOC SLICE_X42Y30 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[35]}]
set_property LOC SLICE_X42Y31 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[36]}]
set_property LOC SLICE_X42Y31 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[37]}]
set_property LOC SLICE_X42Y31 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[38]}]
set_property LOC SLICE_X42Y31 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[39]}]
set_property LOC SLICE_X42Y32 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[40]}]
set_property LOC SLICE_X42Y32 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[41]}]
set_property LOC SLICE_X42Y32 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[42]}]
set_property LOC SLICE_X42Y32 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[43]}]
set_property LOC SLICE_X42Y33 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[44]}]
set_property LOC SLICE_X42Y33 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[45]}]
set_property LOC SLICE_X42Y33 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[46]}]
set_property LOC SLICE_X42Y33 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[47]}]
set_property LOC SLICE_X42Y34 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[48]}]
set_property LOC SLICE_X42Y34 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[49]}]
set_property LOC SLICE_X42Y34 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[50]}]
set_property LOC SLICE_X42Y34 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[51]}]
set_property LOC SLICE_X42Y35 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[52]}]
set_property LOC SLICE_X42Y35 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[53]}]
set_property LOC SLICE_X42Y35 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[54]}]
set_property LOC SLICE_X42Y35 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[55]}]
set_property LOC SLICE_X42Y36 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[56]}]
set_property LOC SLICE_X42Y36 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[57]}]
set_property LOC SLICE_X42Y36 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[58]}]
set_property LOC SLICE_X42Y36 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[59]}]
set_property LOC SLICE_X42Y37 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[60]}]
set_property LOC SLICE_X42Y37 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[61]}]
set_property LOC SLICE_X42Y37 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[62]}]
set_property LOC SLICE_X42Y37 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[63]}]
set_property LOC SLICE_X42Y38 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[64]}]
set_property LOC SLICE_X42Y38 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[65]}]
set_property LOC SLICE_X42Y38 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[66]}]
set_property LOC SLICE_X42Y38 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[67]}]
set_property LOC SLICE_X42Y39 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[68]}]
set_property LOC SLICE_X42Y39 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[69]}]
set_property LOC SLICE_X42Y39 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[70]}]
set_property LOC SLICE_X42Y39 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[71]}]
set_property LOC SLICE_X42Y40 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[72]}]
set_property LOC SLICE_X42Y40 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[73]}]
set_property LOC SLICE_X42Y40 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[74]}]
set_property LOC SLICE_X42Y40 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[75]}]
set_property LOC SLICE_X42Y41 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[76]}]
set_property LOC SLICE_X42Y41 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[77]}]
set_property LOC SLICE_X42Y41 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[78]}]
set_property LOC SLICE_X42Y41 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[79]}]
set_property LOC SLICE_X42Y42 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[80]}]
set_property LOC SLICE_X42Y42 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[81]}]
set_property LOC SLICE_X42Y42 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[82]}]
set_property LOC SLICE_X42Y42 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[83]}]
set_property LOC SLICE_X42Y43 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[84]}]
set_property LOC SLICE_X42Y43 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[85]}]
set_property LOC SLICE_X42Y43 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[86]}]
set_property LOC SLICE_X42Y43 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[87]}]
set_property LOC SLICE_X42Y44 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[88]}]
set_property LOC SLICE_X42Y44 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[89]}]
set_property LOC SLICE_X42Y44 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[90]}]
set_property LOC SLICE_X42Y44 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[91]}]
set_property LOC SLICE_X42Y45 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[92]}]
set_property LOC SLICE_X42Y45 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[93]}]
set_property LOC SLICE_X42Y45 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[94]}]
set_property LOC SLICE_X42Y45 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[95]}]
set_property LOC SLICE_X42Y46 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[96]}]
set_property LOC SLICE_X42Y46 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[97]}]
set_property LOC SLICE_X42Y46 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[98]}]
set_property LOC SLICE_X42Y46 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[99]}]
set_property LOC SLICE_X42Y47 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[100]}]
set_property LOC SLICE_X42Y47 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[101]}]
set_property LOC SLICE_X42Y47 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[102]}]
set_property LOC SLICE_X42Y47 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[103]}]
set_property LOC SLICE_X42Y48 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[104]}]
set_property LOC SLICE_X42Y48 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[105]}]
set_property LOC SLICE_X42Y48 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[106]}]
set_property LOC SLICE_X42Y48 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[107]}]
set_property LOC SLICE_X42Y49 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[108]}]
set_property LOC SLICE_X42Y49 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[109]}]
set_property LOC SLICE_X42Y49 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[110]}]
set_property LOC SLICE_X42Y49 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[111]}]
set_property LOC SLICE_X42Y50 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[112]}]
set_property LOC SLICE_X42Y50 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[113]}]
set_property LOC SLICE_X42Y50 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[114]}]
set_property LOC SLICE_X42Y50 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[115]}]
set_property LOC SLICE_X42Y51 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[116]}]
set_property LOC SLICE_X42Y51 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[117]}]
set_property LOC SLICE_X42Y51 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[118]}]
set_property LOC SLICE_X42Y51 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[119]}]
set_property LOC SLICE_X42Y52 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[120]}]
set_property LOC SLICE_X42Y52 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[121]}]
set_property LOC SLICE_X42Y52 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[122]}]
set_property LOC SLICE_X42Y52 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[123]}]
set_property LOC SLICE_X42Y53 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[124]}]
set_property LOC SLICE_X42Y53 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[125]}]
set_property LOC SLICE_X42Y53 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[126]}]
set_property LOC SLICE_X42Y53 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[127]}]
set_property LOC SLICE_X42Y54 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[128]}]
set_property LOC SLICE_X42Y54 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[129]}]
set_property LOC SLICE_X42Y54 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[130]}]
set_property LOC SLICE_X42Y54 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[131]}]
set_property LOC SLICE_X42Y55 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[132]}]
set_property LOC SLICE_X42Y55 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[133]}]
set_property LOC SLICE_X42Y55 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[134]}]
set_property LOC SLICE_X42Y55 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[135]}]
set_property LOC SLICE_X42Y56 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[136]}]
set_property LOC SLICE_X42Y56 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[137]}]
set_property LOC SLICE_X42Y56 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[138]}]
set_property LOC SLICE_X42Y56 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[139]}]
set_property LOC SLICE_X42Y57 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[140]}]
set_property LOC SLICE_X42Y57 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[141]}]
set_property LOC SLICE_X42Y57 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[142]}]
set_property LOC SLICE_X42Y57 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[143]}]
set_property LOC SLICE_X42Y58 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[144]}]
set_property LOC SLICE_X42Y58 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[145]}]
set_property LOC SLICE_X42Y58 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[146]}]
set_property LOC SLICE_X42Y58 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[147]}]
set_property LOC SLICE_X42Y59 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[148]}]
set_property LOC SLICE_X42Y59 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[149]}]
set_property LOC SLICE_X42Y59 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[150]}]
set_property LOC SLICE_X42Y59 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[151]}]
set_property LOC SLICE_X42Y60 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[152]}]
set_property LOC SLICE_X42Y60 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[153]}]
set_property LOC SLICE_X42Y60 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[154]}]
set_property LOC SLICE_X42Y60 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[155]}]
set_property LOC SLICE_X42Y61 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[156]}]
set_property LOC SLICE_X42Y61 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[157]}]
set_property LOC SLICE_X42Y61 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[158]}]
set_property LOC SLICE_X42Y61 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[159]}]
set_property LOC SLICE_X42Y62 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[160]}]
set_property LOC SLICE_X42Y62 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[161]}]
set_property LOC SLICE_X42Y62 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[162]}]
set_property LOC SLICE_X42Y62 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[163]}]
set_property LOC SLICE_X42Y63 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[164]}]
set_property LOC SLICE_X42Y63 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[165]}]
set_property LOC SLICE_X42Y63 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[166]}]
set_property LOC SLICE_X42Y63 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[167]}]
set_property LOC SLICE_X42Y64 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[168]}]
set_property LOC SLICE_X42Y64 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[169]}]
set_property LOC SLICE_X42Y64 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[170]}]
set_property LOC SLICE_X42Y64 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[171]}]
set_property LOC SLICE_X42Y65 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[172]}]
set_property LOC SLICE_X42Y65 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[173]}]
set_property LOC SLICE_X42Y65 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[174]}]
set_property LOC SLICE_X42Y65 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[175]}]
set_property LOC SLICE_X42Y66 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[176]}]
set_property LOC SLICE_X42Y66 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[177]}]
set_property LOC SLICE_X42Y66 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[178]}]
set_property LOC SLICE_X42Y66 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[179]}]
set_property LOC SLICE_X42Y67 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[180]}]
set_property LOC SLICE_X42Y67 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[181]}]
set_property LOC SLICE_X42Y67 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[182]}]
set_property LOC SLICE_X42Y67 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[183]}]
set_property LOC SLICE_X42Y68 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[184]}]
set_property LOC SLICE_X42Y68 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[185]}]
set_property LOC SLICE_X42Y68 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[186]}]
set_property LOC SLICE_X42Y68 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[187]}]
set_property LOC SLICE_X42Y69 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[188]}]
set_property LOC SLICE_X42Y69 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[189]}]
set_property LOC SLICE_X42Y69 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[190]}]
set_property LOC SLICE_X42Y69 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[191]}]
set_property LOC SLICE_X42Y70 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[192]}]
set_property LOC SLICE_X42Y70 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[193]}]
set_property LOC SLICE_X42Y70 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[194]}]
set_property LOC SLICE_X42Y70 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[195]}]
set_property LOC SLICE_X42Y71 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[196]}]
set_property LOC SLICE_X42Y71 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[197]}]
set_property LOC SLICE_X42Y71 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[198]}]
set_property LOC SLICE_X42Y71 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[199]}]
set_property LOC SLICE_X42Y72 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[200]}]
set_property LOC SLICE_X42Y72 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[201]}]
set_property LOC SLICE_X42Y72 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[202]}]
set_property LOC SLICE_X42Y72 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[203]}]
set_property LOC SLICE_X42Y73 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[204]}]
set_property LOC SLICE_X42Y73 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[205]}]
set_property LOC SLICE_X42Y73 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[206]}]
set_property LOC SLICE_X42Y73 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[207]}]
set_property LOC SLICE_X42Y74 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[208]}]
set_property LOC SLICE_X42Y74 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[209]}]
set_property LOC SLICE_X42Y74 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[210]}]
set_property LOC SLICE_X42Y74 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[211]}]
set_property LOC SLICE_X42Y75 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[212]}]
set_property LOC SLICE_X42Y75 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[213]}]
set_property LOC SLICE_X42Y75 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[214]}]
set_property LOC SLICE_X42Y75 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[215]}]
set_property LOC SLICE_X42Y76 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[216]}]
set_property LOC SLICE_X42Y76 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[217]}]
set_property LOC SLICE_X42Y76 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[218]}]
set_property LOC SLICE_X42Y76 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[219]}]
set_property LOC SLICE_X42Y77 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[220]}]
set_property LOC SLICE_X42Y77 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[221]}]
set_property LOC SLICE_X42Y77 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[222]}]
set_property LOC SLICE_X42Y77 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[223]}]
set_property LOC SLICE_X42Y78 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[224]}]
set_property LOC SLICE_X42Y78 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[225]}]
set_property LOC SLICE_X42Y78 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[226]}]
set_property LOC SLICE_X42Y78 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[227]}]
set_property LOC SLICE_X42Y79 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[228]}]
set_property LOC SLICE_X42Y79 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[229]}]
set_property LOC SLICE_X42Y79 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[230]}]
set_property LOC SLICE_X42Y79 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[231]}]
set_property LOC SLICE_X42Y80 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[232]}]
set_property LOC SLICE_X42Y80 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[233]}]
set_property LOC SLICE_X42Y80 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[234]}]
set_property LOC SLICE_X42Y80 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[235]}]
set_property LOC SLICE_X42Y81 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[236]}]
set_property LOC SLICE_X42Y81 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[237]}]
set_property LOC SLICE_X42Y81 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[238]}]
set_property LOC SLICE_X42Y81 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[239]}]
set_property LOC SLICE_X42Y82 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[240]}]
set_property LOC SLICE_X42Y82 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[241]}]
set_property LOC SLICE_X42Y82 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[242]}]
set_property LOC SLICE_X42Y82 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[243]}]
set_property LOC SLICE_X42Y83 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[244]}]
set_property LOC SLICE_X42Y83 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[245]}]
set_property LOC SLICE_X42Y83 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[246]}]
set_property LOC SLICE_X42Y83 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[247]}]
set_property LOC SLICE_X42Y84 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[248]}]
set_property LOC SLICE_X42Y84 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[249]}]
set_property LOC SLICE_X42Y84 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[250]}]
set_property LOC SLICE_X42Y84 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[251]}]
set_property LOC SLICE_X42Y85 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[252]}]
set_property LOC SLICE_X42Y85 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[253]}]
set_property LOC SLICE_X42Y85 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[254]}]
set_property LOC SLICE_X42Y85 [get_cells {i_quantum_tagger/r_tdl_ch1_d_reg[255]}]



############################################################################
# Clock constraints                                                        #
############################################################################

#NET "adc_clk" TNM_NET = "adc_clk";
#TIMESPEC TS_adc_clk = PERIOD "adc_clk" 125 MHz;

create_clock -period 8.000 -name adc_clk [get_ports adc_clk_i[1]]

set_input_delay -clock adc_clk 3.400 [get_ports adc_dat_i[*][*]]

create_clock -period 4.000 -name rx_clk  [get_ports daisy_p_i[1]]

create_clock -period 8.000 -name dac_clk_o  [get_ports dac_clk_o]
create_clock -period 8.000 -name dac_clk_o  [get_ports dac_clk_1x]
create_clock -period 8.000 -name dac_clk_o  [get_ports dac_clk_2x]
create_clock -period 8.000 -name dac_clk_o  [get_ports dac_clk_2p]

set_false_path -from [get_clocks adc_clk]     -to [get_clocks dac_clk_o]
set_false_path -from [get_clocks adc_clk]     -to [get_clocks dac_clk_2x]
set_false_path -from [get_clocks adc_clk]     -to [get_clocks dac_clk_2p]
set_false_path -from [get_clocks pll_adc_clk] -to [get_clocks pll_dac_clk_2x]
set_false_path -from [get_clocks adc_clk]     -to [get_clocks pll_adc_clk]

set_false_path -from [get_clocks par_clk]     -to [get_clocks pll_adc_clk]

set_false_path -from [get_clocks clk_fpga_0]  -to [get_clocks dac_clk_1x]
set_false_path -from [get_clocks clk_fpga_0]  -to [get_clocks dac_clk_2x]
set_false_path -from [get_clocks clk_fpga_0]  -to [get_clocks dac_clk_2p]
set_false_path -from [get_clocks clk_fpga_0]  -to [get_clocks ser_clk]
set_false_path -from [get_clocks clk_fpga_0]  -to [get_clocks pdm_clk]
set_false_path -from [get_clocks dac_clk_o] -to [get_clocks dac_clk_2x]
set_false_path -from [get_clocks dac_clk_o] -to [get_clocks dac_clk_2p]
set_false_path -from [get_clocks pll_adc_clk] -to [get_clocks par_clk]
